CREATE TABLESPACE TR_PORTALPRODUTOS_DATA DATAFILE 'TR_PORTALPRODUTOS_DATA01.ora' SIZE 5M AUTOEXTEND ON NEXT  10M MAXSIZE  2000M FORCE logging;

CREATE TABLESPACE TR_PORTALPRODUTOS_INDEX DATAFILE 'TR_PORTALPRODUTOS_INDEX01.ora' SIZE 5M AUTOEXTEND ON NEXT  10M MAXSIZE 2000M FORCE logging;

CREATE USER TRPORTALPRODUTOS IDENTIFIED BY TRPORTALPRODUTOS 
DEFAULT TABLESPACE TR_PORTALPRODUTOS_DATA 
QUOTA UNLIMITED ON TR_PORTALPRODUTOS_DATA
QUOTA UNLIMITED ON TR_PORTALPRODUTOS_INDEX;

grant alter session,
create database link,
create procedure,
create sequence,
create session,
create synonym,
create table,
create trigger,
create type,
create view,
create snapshot,
debug any procedure,
debug connect session to TRPORTALPRODUTOS;

grant select on v_$session to TRPORTALPRODUTOS;
grant execute on DBMS_CRYPTO to TRPORTALPRODUTOS;